name: Hello World
on: [push]
jobs:
        Run_All_Labs:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: Running All Lab Exercises
                          run: make ci_cd_workflow

        Lab_1:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: Running Lab 1
                        - run: make lab1

        Lab_2:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: Running Lab 2
                        - run: make lab2

        Lab_3:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: Running Lab 3
                        - run: make lab3

        Lab_4:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: Running Lab 4
                        - run: make lab4

        Lab_5:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: Running Lab 5
                        - run: make lab5

        Lab_7:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: Running Lab 7
                        - run: make lab7

        Lab_9:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3
                        - name: Running Lab 9
                        - run: make lab9
