name: Hello World
on: [push]
jobs:
        HelloWorld:
                runs-on: ubuntu-latest

                steps:
                        - uses: actions/checkout@v3
                        - run: echo "Running makefile"
                        - name: Lab Exercise 1
                          run: make lab1
