name: Hello World
on: [push]
jobs:
        Run_All_Labs:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v3

                        - name: Running All Lab Exercises
                          run: make ci_cd_workflow

                        - name: Running Lab 1
                          run: make cicd_lab1

                        - name: Running Lab 2
                          run: make cicd_lab2

                        - name: Running Lab 3
                          run: make cicd_lab3

                        - name: Running Lab 4
                          run: make cicd_lab4

                        - name: Running Lab 5
                          run: make cicd_lab5

                        - name: Running Lab 7
                          run: make cicd_lab7

                        - name: Running Lab 9
                          run: make cicd_lab9
